export const cuisinesList = [
    "American",
    "BBQ",
    "Breakfast",
    "Indian (North)",
    "Indian (South)",
    "Chinese",
    "Italian",
    "Mexican",
    "Thai",
    "Japanese",
    "Middle Eastern",
    "Bengali",
    "Continental",
    "French",
    "Greek",
    "Korean",
    "Spanish",
    "Vietnamese",
    "Healthy",
    "Salad",
    "Vegetarian",
    "Vegan",
    "Gluten-free",
    "Organic",
    "Smoothies",
    "Juices"
];